name: Cargo Build & Test
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  MongoStr: mongodb://127.0.0.1:27017/test

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        #          - beta
        #          - nightly
        mongodb-version: [ '6.0' ]
    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs1
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install Rust
        run: rustup update stable
      - uses: Swatinem/rust-cache@v2
      - name: test mscheduler all features
        run: cargo test --all-features
